code_api:
  resource: "@EvrinomaCodeBundle/Controller/CodeApiController.php"
  type: annotation

code_owner_api:
  resource: "@EvrinomaCodeBundle/Controller/OwnerApiController.php"
  type: annotation

code_type_api:
  resource: "@EvrinomaCodeBundle/Controller/TypeApiController.php"
  type: annotation

code_bunch_api:
  resource: "@EvrinomaCodeBundle/Controller/BunchApiController.php"
  type: annotation

code_bind_api:
  resource: "@EvrinomaCodeBundle/Controller/BindApiController.php"
  type: annotation
