services:
  Evrinoma\CodeBundle\Controller\TypeApiController:
    alias: evrinoma.code.type.api.controller
    public: true

  evrinoma.code.type.api.controller:
    class: Evrinoma\CodeBundle\Controller\TypeApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.code.type.command.manager'
      - '@evrinoma.code.type.query.manager'
    autowire: true

  evrinoma.code.type.factory:
    class: Evrinoma\CodeBundle\Factory\TypeFactory
    public: true
    arguments:

  evrinoma.code.type.repository:
    class: Evrinoma\CodeBundle\Repository\Type\TypeRepository
    public: true
    arguments:

  evrinoma.code.type.command.manager:
    class: Evrinoma\CodeBundle\Manager\Type\CommandManager
    arguments:
      - '@evrinoma.code.type.validator'
      - '@evrinoma.code.type.repository'
      - '@evrinoma.code.type.factory'

  evrinoma.code.type.query.manager:
    class: Evrinoma\CodeBundle\Manager\Type\QueryManager
    arguments:
      - '@evrinoma.code.type.repository'

  evrinoma.code.type.validator:
    class: Evrinoma\CodeBundle\Validator\TypeValidator
    public: true
    arguments:
      - '@validator'

  Evrinoma\CodeBundle\Validator\TypeValidator:
    alias: evrinoma.code.type.validator

  evrinoma.code.form.rest.type:
    class: Evrinoma\CodeBundle\Form\Rest\CodeTypeChoiceType
    arguments:
      - '@evrinoma.code.type.query.manager'
    tags: { - name: form.type }

  Evrinoma\CodeBundle\Form\Rest\CodeTypeChoiceType:
    alias: evrinoma.code.form.rest.type
    public: true
