imports:
  - { resource: services/owner.yml }
  - { resource: services/type.yml }
  - { resource: services/bunch.yml }

services:
  Evrinoma\CodeBundle\Controller\CodeApiController:
    alias: evrinoma.code.api.controller
    public: true

  evrinoma.code.api.controller:
    class: Evrinoma\CodeBundle\Controller\CodeApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.code.command.manager'
      - '@evrinoma.code.query.manager'

  evrinoma.code.command.manager:
    class: Evrinoma\CodeBundle\Manager\CommandManager

  evrinoma.code.query.manager:
    class: Evrinoma\CodeBundle\Manager\QueryManager
