services:
  Evrinoma\CodeBundle\Controller\CodeApiController:
    alias: evrinoma.code.api.controller
    public: true

  evrinoma.code.api.controller:
    class: Evrinoma\CodeBundle\Controller\CodeApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.code.command.manager'
      - '@evrinoma.code.query.manager'

  evrinoma.code.command.manager:
    class: Evrinoma\CodeBundle\Manager\CommandManager

  evrinoma.code.query.manager:
    class: Evrinoma\CodeBundle\Manager\QueryManager

  evrinoma.code.validator.owner:
    class: Evrinoma\CodeBundle\Validator\OwnerValidator
    public: true
    arguments:

  Evrinoma\CodeBundle\Validator\OwnerValidator:
    alias: evrinoma.code.validator.owner
