services:
  evrinoma.code.constraint.owner.brief:
    class: Evrinoma\CodeBundle\Constraint\Owner\Brief

  evrinoma.code.constraint.owner.description:
    class: Evrinoma\CodeBundle\Constraint\Owner\Description

  evrinoma.code.constraint.type.brief:
    class: Evrinoma\CodeBundle\Constraint\Type\Brief

