services:
  evrinoma.code.constraint.bind.property.bunch:
    class: Evrinoma\CodeBundle\Constraint\Property\Bind\Bunch

  evrinoma.code.constraint.bind.property.code:
    class: Evrinoma\CodeBundle\Constraint\Property\Bind\Code


