services:
  evrinoma.code.constraint.bunch.property.description:
    class: Evrinoma\CodeBundle\Constraint\Property\Bunch\Description

  evrinoma.code.constraint.bunch.property.type:
    class: Evrinoma\CodeBundle\Constraint\Property\Bunch\Type


