services:
  evrinoma.code.constraint.code.description:
    class: Evrinoma\CodeBundle\Constraint\Code\Description

  evrinoma.code.constraint.code.brief:
    class: Evrinoma\CodeBundle\Constraint\Code\Brief

  evrinoma.code.constraint.code.bunch:
    class: Evrinoma\CodeBundle\Constraint\Code\Bunch

  evrinoma.code.constraint.code.owner:
    class: Evrinoma\CodeBundle\Constraint\Code\Owner

