services:
  evrinoma.code.constraint.code.property.description:
    class: Evrinoma\CodeBundle\Constraint\Property\Code\Description

  evrinoma.code.constraint.code.property.brief:
    class: Evrinoma\CodeBundle\Constraint\Property\Code\Brief

  evrinoma.code.constraint.code.property.type:
    class: Evrinoma\CodeBundle\Constraint\Property\Code\Type

  evrinoma.code.constraint.code.property.owner:
    class: Evrinoma\CodeBundle\Constraint\Property\Code\Owner

