services:
  evrinoma.code.constraint.owner.property.brief:
    class: Evrinoma\CodeBundle\Constraint\Property\Owner\Brief

  evrinoma.code.constraint.owner.property.description:
    class: Evrinoma\CodeBundle\Constraint\Property\Owner\Description


